@DaprAcaStarter_HostAddress = http://localhost:8080

### Health
GET {{DaprAcaStarter_HostAddress}}/healthz
Accept: application/json

### Service Metadata
GET {{DaprAcaStarter_HostAddress}}/
Accept: application/json

### Get Products (storefront -> products-service)
GET {{DaprAcaStarter_HostAddress}}/api/products
Accept: application/json

### Add To Cart (storefront -> cart-service)
POST {{DaprAcaStarter_HostAddress}}/api/cart/cust-101/items
Content-Type: application/json

{
  "productId": "P-400",
  "productName": "Laptop Stand",
  "unitPrice": 39.99,
  "quantity": 2
}

### Checkout (storefront -> checkout-service)
POST {{DaprAcaStarter_HostAddress}}/api/checkout/cust-101
Content-Type: application/json

{}

### Read Cart
GET {{DaprAcaStarter_HostAddress}}/api/cart/cust-101
Accept: application/json

### Load Order By Id
GET {{DaprAcaStarter_HostAddress}}/api/orders/<ORDER_ID>
Accept: application/json
